- hosts: localhost
  tasks:
  - name: install Git
    yum: name=git state=latest
    become: yes
    become_method: sudo      
  - name: clone myrepo
    git: repo=https://github.com/Matti2010/myrepo.git dest=/home/ec2-user/myrepo update=no
  - name: clone petclinic
    git: repo=https://github.com/Matti2010/spring-petclinic.git dest=/home/ec2-user/petclinic 
  - name: mkdir ~/maven
    file: path=~/maven state=directory mode=0755
  - name: install maven
    unarchive: src="http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz" dest="/home/ec2-user/maven" copy=no creates=~/maven/apache-maven-3.3.9/README.txt
  - name: set maven env
    lineinfile: dest=~/.bash_profile state=present line="export M2_HOME=~/maven/apache-maven-3.3.9"
  - name: set maven env
    lineinfile: dest=~/.bash_profile state=present line="export M2=${M2_HOME}/bin"
  - name: set maven env
    lineinfile: dest=~/.bash_profile state=present line="export PATH=$M2:$PATH"
  - name: install docker
    yum: name=docker state=latest
    become: yes
    become_method: sudo
  - name: add group docker to user ec2-user
    user: append=yes groups=docker name=ec2-user 
    become: yes
    become_method: sudo
  - name: start docker service
    service: name=docker state=started
    become: yes
    become_method: sudo
  - name: Ensure Jenkins Yum repo present
    become: yes
    become_method: sudo
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
           dest=/etc/yum.repos.d/jenkins.repo mode=0644
  - name: Ensure Jenkins GPG key installed
    command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    become: yes
    become_method: sudo
  - name: Ensure Jenkins installed
    yum: name=jenkins state=present
    become: yes
    become_method: sudo
  - name: Ensure Jenkins is running
    service: name=jenkins state=running enabled=true
    become: yes
    become_method: sudo 
