- hosts: localhost
  tasks:
  - name: install Git
    yum: name=git state=latest
    become: yes
    become_method: sudo      
  - name: clone myrepo
    git: repo=https://github.com/Matti2010/myrepo.git dest=/home/ec2-user/myrepo 
  - name: clone petclinic
    git: repo=https://github.com/Matti2010/spring-petclinic.git dest=/home/ec2-user/petclinic
